In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


Creating Tensor

In [ ]:
# using empty
a = torch.empty(2,3)
print(a)

tensor([[7.9504e-16, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)   # useful in creating weight initialization matrix

tensor([[0.1257, 0.7340, 0.3441],
        [0.8254, 0.4348, 0.4061]])

In [ ]:
# use of seed
torch.rand(2,3)  # different value as above

tensor([[0.9149, 0.6062, 0.9969],
        [0.5891, 0.7050, 0.7496]])

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)              # getting same values

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor

torch.tensor([[1,2,3],[4,5,6]])  # make custom tensors

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))  # 5X5 identity matrix

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [ ]:
X = torch.tensor([[1,2,3],[4,5,6]])
print(X.shape)

torch.Size([2, 3])


In [ ]:
torch.empty_like(X)

tensor([[644463104, 644303216,     65536],
        [        1,        48,        96]])

In [ ]:
torch.zeros_like(X)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(X)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(X, dtype = torch.float)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Mathematical Operations

1) Scalar Operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

2) Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])
tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1784, 0.3346, 0.0706],
        [0.2767, 0.4440, 0.2063]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3) Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[0., 9., 5.],
        [7., 3., 9.]])

In [ ]:
# sum
torch.sum(e)

tensor(33.)

In [ ]:
# sum along columns
torch.sum(e, dim=0)

tensor([ 7., 12., 14.])

In [ ]:
# sum along rows
torch.sum(e, dim=1)

tensor([14., 19.])

In [ ]:
# mean
torch.mean(e) # net total mean
# mean along col
torch.mean(e, dim=0)

tensor([3.5000, 6.0000, 7.0000])

In [ ]:
#median
torch.median(e)

tensor(5.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# argmax
torch.argmax(e)

tensor(1)

In [ ]:
torch.argmin(e)

tensor(0)

4) Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[7, 9, 2],
        [6, 7, 7]])
tensor([[8, 3],
        [6, 1],
        [5, 5]])


In [ ]:
# matrix multiplication
torch.matmul(f, g)

tensor([[120,  40],
        [125,  60]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1) #swap dimension 0 and 1

tensor([[7, 6],
        [9, 7],
        [2, 7]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 4., 3.],
        [8., 8., 3.],
        [3., 5., 0.]])

In [ ]:
# determinant
torch.det(h)

tensor(84.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.1786,  0.1786, -0.1429],
        [ 0.1071, -0.1071,  0.2857],
        [ 0.1905,  0.1429, -0.3810]])

5) Comparison Operations

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[6., 4., 0.],
        [8., 4., 7.]])

In [ ]:
# log
torch.log(k)

tensor([[1.7918, 1.3863,   -inf],
        [2.0794, 1.3863, 1.9459]])

In [ ]:
# exp
torch.exp(k)

tensor([[4.0343e+02, 5.4598e+01, 1.0000e+00],
        [2.9810e+03, 5.4598e+01, 1.0966e+03]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.4495, 2.0000, 0.0000],
        [2.8284, 2.0000, 2.6458]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.9820, 0.5000],
        [0.9997, 0.9820, 0.9991]])

In [ ]:
# softmax
torch.softmax(k, dim=0) # across comumns

tensor([[1.1920e-01, 5.0000e-01, 9.1105e-04],
        [8.8080e-01, 5.0000e-01, 9.9909e-01]])

In [ ]:
# relu
torch.relu(k)

tensor([[6., 4., 0.],
        [8., 4., 7.]])

Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.5548, 0.6868, 0.4920],
        [0.0748, 0.9605, 0.3271]])
tensor([[0.0103, 0.9516, 0.2855],
        [0.2324, 0.9141, 0.7668]])


In [ ]:
m.add_(n)

tensor([[0.5650, 1.6384, 0.7776],
        [0.3072, 1.8746, 1.0939]])

In [ ]:
m

tensor([[0.5650, 1.6384, 0.7776],
        [0.3072, 1.8746, 1.0939]])

In [ ]:
n

tensor([[0.0103, 0.9516, 0.2855],
        [0.2324, 0.9141, 0.7668]])

In [ ]:
torch.relu(m)

tensor([[0.5650, 1.6384, 0.7776],
        [0.3072, 1.8746, 1.0939]])

In [ ]:
m.relu_() # for permanent changes

tensor([[0.5650, 1.6384, 0.7776],
        [0.3072, 1.8746, 1.0939]])

Copying a tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [ ]:
b

tensor([[0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.4393,  0.2243],
        [ 0.8935,  0.0497,  0.1780]])

In [ ]:
b # due to clone value of b did not change when we changed a

tensor([[0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [ ]:
id(a)

135989107245616

In [ ]:
id(b)

135989106973808